### ISSUE TITLE
It resets while i lock workstation

### ISSUE THREAD

**Issue by SecriusV** [aliakseiz/stopwatch#1]
It resets while i lock workstation

Fedora 37, Gnome 43.3, Wayland

**Comment by aliakseiz** [comment]
True, normally Gnome extensions are disabled when the screen is locked.

How would you expect the stopwatch to behave in this situation?

**Comment by aliakseiz** [comment]
> if it still runs — it must count seconds when screen is locked.

For me it looks very similar to the output of the `uptime` command. There are some extensions displaying it, for instance [Vitals](https://extensions.gnome.org/extension/1460/vitals/) can do that.

What would you say about the following scenario?
1. User starts a stopwatch
2. Screen is locked
3. Stopwatch paused and displayed on the lock screen
4. Screen unlocked
5. Stopwatch automatically resumes counting

Or maybe it would be more convenient, if timer remains paused at step #5? Then user might forget to resume.

> I just search timer for encounter my "real" working time. But if there is no way to count seconds when screen is locked, it will acceptable for me, but only if last value will be saved.

Good to know that, thank you. Initially stopwatch was created to track my working time as well.

**Comment by aliakseiz** [comment]
Alright, I've got your point and I agree with it.

Here is what I will do: timer will be paused when the screen is locked and will remain paused after unlocking. It will not reset automatically.

**Comment by SecriusV** [comment]
Yes, it works after restart Gnome session (re-login). And works as we decided above. Thank you!
